In [1]:
import pandas as pd

In [2]:
# Data overview
df = pd.read_csv("../data/processed/processed_smart_logistics_dataset.csv", parse_dates=['Timestamp'])
df.head()

,Timestamp,Asset_ID,Latitude,Longitude,Inventory_Level,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Logistics_Delay_Reason,Asset_Utilization,Demand_Forecast,Logistics_Delay
0,2024-03-20 00:11:14,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,NaN,60.1,285,1
1,2024-10-30 07:53:51,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1
2,2024-07-29 18:42:48,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,NaN,99.2,260,0
3,2024-10-28 00:50:54,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1
4,2024-09-27 15:52:58,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,NaN,71.6,270,1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Timestamp                1000 non-null   datetime64[us]
 1   Asset_ID                 1000 non-null   str
 2   Latitude                 1000 non-null   float64
 3   Longitude                1000 non-null   float64
 4   Inventory_Level          1000 non-null   int64
 5   Shipment_Status          1000 non-null   str
 6   Temperature              1000 non-null   float64
 7   Humidity                 1000 non-null   float64
 8   Traffic_Status           1000 non-null   str
 9   Waiting_Time             1000 non-null   int64
 10  User_Transaction_Amount  1000 non-null   int64
 11  User_Purchase_Frequency  1000 non-null   int64
 12  Logistics_Delay_Reason   737 non-null    str
 13  Asset_Utilization        1000 non-null   float64
 14  Demand_Forecast          1000 non-null   int64
 15  Logistics_Delay          1000 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(6), str(4)
memory usage: 125.1 KB

In [4]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Timestamp,1000,2024-06-30 23:15:56.539000,2024-01-01 11:37:57,2024-03-27 01:27:56.500000,2024-07-01 03:30:16.500000,2024-10-02 13:30:34.500000,2024-12-30 20:21:58,NaN
Latitude,1000.0,-1.360093,-89.7915,-46.167975,-4.50315,44.5028,89.8701,51.997183
Longitude,1000.0,0.837049,-179.8202,-88.448075,0.6783,88.15645,179.9237,104.843618
Inventory_Level,1000.0,297.915,100.0,201.0,299.0,399.0,500.0,113.554773
Temperature,1000.0,23.8939,18.0,21.2,23.8,26.6,30.0,3.322178
Humidity,1000.0,65.0422,50.0,57.2,65.2,72.4,80.0,8.753765
Waiting_Time,1000.0,35.062,10.0,23.0,35.0,49.0,60.0,14.477768
User_Transaction_Amount,1000.0,299.055,100.0,191.75,301.5,405.0,500.0,117.787792
User_Purchase_Frequency,1000.0,5.513,1.0,3.0,6.0,8.0,10.0,2.935379
Asset_Utilization,1000.0,79.5991,60.0,69.475,79.25,89.425,100.0,11.631153
Demand_Forecast,1000.0,199.284,100.0,144.0,202.0,251.25,300.0,59.920847
Logistics_Delay,1000.0,0.566,0.0,0.0,1.0,1.0,1.0,0.495873

Since the data includes latitude & longitude + demand nodes -> we can solve a capacitated VRP

##### For capacitated VRP, we require:
- Coordinates
- Demand
- Depot
- Vehicle Capacity
- Number of Vehicles

In [5]:
len(df)

1000

Since the length of nodes is large, we first need to cluster nodes, and then solve VRP per cluster. After all, we need to combine routes to get a feasible solution.

* Step 1: Prepare routing dataframe
* Step 2: Cluster nodes
* Step 3: Solve VRP per cluster
* Step 4: Aggregate routes