In [1]:
import sys
import os
import pandas as pd
PROJECT_ROOT = os.path.abspath("..")
sys.path.append(PROJECT_ROOT)

from src.visualizer.route_visualizer import RouteVisualizer
from src.optimization.vrp_solver import VRPsolver
from IPython.display import IFrame, display, HTML
from src.utils.artifact_io import load_cluster_artifact

In [2]:
df = pd.read_csv("../data/final/smart_logistics_dataset_with_clusters.csv")
df.head()

,Latitude,Longitude,Demand_Forecast,Traffic_Status,Waiting_Time,Traffic_Encoded,Cluster_ID
0,-65.7383,11.2497,285,Detour,38,2,5
1,22.2748,-131.7086,174,Heavy,16,3,7
2,54.9232,79.5455,260,Detour,34,2,8
3,42.3900,-1.4788,160,Heavy,37,3,12
4,-65.8477,47.9468,270,Clear,56,1,16

In [3]:
# sample cluster
cluster_id = 0
cluster_df = df[df['Cluster_ID'] == cluster_id].copy().reset_index(drop=True)
cluster_df

,Latitude,Longitude,Demand_Forecast,Traffic_Status,Waiting_Time,Traffic_Encoded,Cluster_ID
0,2.6709,-80.8879,231,Heavy,54,3,0
1,5.9179,74.8254,242,Heavy,39,3,0
2,80.3158,70.7650,205,Heavy,45,3,0
3,-19.2577,66.7440,266,Heavy,50,3,0
4,79.1172,178.4934,242,Heavy,40,3,0
...,...,...,...,...,...,...,...
67,-30.9460,-65.5352,232,Heavy,41,3,0
68,-31.9959,164.6097,226,Heavy,47,3,0
69,84.8041,86.1533,246,Heavy,37,3,0
70,0.4055,97.6022,202,Heavy,57,3,0
71,14.1533,164.1186,283,Heavy,50,3,0

In [4]:
# Load routes
artifact = load_cluster_artifact(cluster_id = cluster_id)

routes = artifact['routes']
metrics = artifact['metrics']

metrics

FileNotFoundError: Artifact not found on: /Users/gorkemy/Desktop/Projects/Smart Logistics Planner - Supply Chain/data/outputs/artifacts/cluster_0_artifact.json

In [ ]:
# artificial depot row
depot_lat = cluster_df['Latitude'].mean()
depot_lon = cluster_df['Longitude'].mean()

depot_row = {
    'Latitude': depot_lat,
    'Longitude': depot_lon,
    'Demand_Forecast': 0,
    'Traffic_Status': cluster_df['Traffic_Status'].iloc[0],
    'Waiting_Time': cluster_df['Waiting_Time'].median(),
    'Traffic_Encoded': cluster_df['Traffic_Encoded'].mean(),
    'Cluster_ID': cluster_df['Cluster_ID'].mean()
}

cluster_df_with_depot = pd.concat(
    [cluster_df, pd.DataFrame([depot_row])],
    ignore_index = True
)

cluster_df_with_depot

In [ ]:
# Visualizer
visualizer = RouteVisualizer(depot_lat, depot_lon)

m, map_path = visualizer.visualize_cluster_routes(
    cluster_df = cluster_df, # cluster_df_with_depot,
    routes = routes,
    cluster_id = cluster_id
)

m

In [ ]:
# saving static image for a preview on github
visualizer.save_static_image(map_path)